---
- name: "template zone files"
  when: item.value.state == "present"
  template:
    src: "etc-firewalld-zones-zone.xml.j2"
    dest: "/etc/firewalld/zones/{{ item.value.key }}.xml"
  with_dict: "{{ aspects_firewalld_zones }}"
#  notify: restart firewalld
  tags:
  - aspects_firewalld
  - aspects_firewalld_template_tasks

- name: "remove unwanted zone files."
  when: item.value.state == "absent"
  file:
    state: "absent"
    name: "/etc/firewalld/zones/{{ item.value.key }}.xml"
  with_dict: "{{ aspects_firewalld_zones }}"
#  notify: restart firewalld
  tags:
  - aspects_firewalld
  - aspects_firewalld_template_tasks
