---
- name: restart firewalld
  service:
    name: firewalld
    state: restarted
    enabled: yes
  register: aspects_firewalld_service_restarted
  tags:
  - aspects_firewalld

- name: reload firewalld
  service:
    name: firewalld
    state: reloaded
    enabled: yes
  register: aspects_firewalld_service_reloaded
  tags:
  - aspects_firewalld

- name: start firewalld
  service:
    name: firewalld
    state: started
    enabled: yes
  register: aspects_firewalld_service_started
  tags:
  - aspects_firewalld

- name: stop firewalld
  service:
    name: firewalld
    state: stopped
  register: aspects_firewalld_service_stopped
  tags:
  - aspects_firewalld